$background = 0xff161616
$overlay1 = 0xff252525
$overlay2 = 0xff353535
$foreground = 0xffF2F4F8

$black = 0xff252525
$red = 0xffEE5396
$green = 0xff25BE6A
$orange = 0xff08BDBA
$blue = 0xff78A9FF
$mauve = 0xffBE95FF
$sky = 0xff33B1FF
