$background = 0xff1F1F28
$overlay1 = 0xff2A2A37
$overlay2 = 0xff363646
$foreground = 0xffDCD7BA

$black = 0xff16161D
$red = 0xffE46876
$green = 0xff98BB6C
$orange = 0xffE6C384
$blue = 0xff7E9CD8
$mauve = 0xff957FB8
$sky = 0xff7FB4CA
