$background = 0xff1f2335
$overlay1 = 0xff24283b
$overlay2 = 0xff292e42
$foreground = 0xffa9b1d6

$black = 0xff15161e
$red = 0xfff7768e
$green = 0xff9ece6a
$orange = 0xffe0af68
$blue = 0xff7aa2f7
$mauve = 0xffbb9af7
$sky = 0xff7dcfff
