source = $HOME/.config/hypr/themes/tokyonight.conf

$accent = $sky
$accentAlpha = $red
$font = GeistMono Nerd Font

# GENERAL
general {
    disable_loading_bar = true
    hide_cursor = true
}

# BACKGROUND
background {
    monitor =
    path = ~/wallpapers/wew.jpg
    blur_passes = 2
    blur_size = 4
    color = $base
}

# TIME
label {
    monitor =
    text = cmd[update:30000] echo "$(date +"%R")"
    color = $foreground
    font_size = 90
    font_family = $font
    position = -30, 0
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
    color = $foreground
    font_size = 25
    font_family = $font
    position = -30, -150
    halign = right
    valign = top
}

# USER AVATAR

image {
    monitor =
    path = ~/.face
    size = 100
    border_color = $overlay1

    position = 0, 75
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $overlay1
    inner_color = $overlay2
    font_color = $foreground
    fade_on_empty = false
    placeholder_text = <span foreground="##e0def4" font_family="GeistMono Nerd Font"><span font_family="GeistMono Nerd Font"> </span>Logged in as <span foreground="##c4a7e7">$USER</span></span>
    hide_input = false
    check_color = $overlay1
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $orange
    position = 0, -35
    halign = center
    valign = center
}
