add_newline = true

format = """\
  [➜](green) \
  $directory\
  $git_branch\
  $character\
  """

[directory]
truncation_length = 6
truncate_to_repo = true
disabled = false

[hostname]
ssh_only = false
format = "[$hostname]($style) in "
trim_at = "."
disabled = false

[line_break]
disabled = false

[username]
style_root = "bold red"
style_user = "bold yellow"
show_always = false
disabled = false
